require('dotenv').config();
const path = require('path');

const { env } = process;

const config = {
  PORT: env.PORT || 4000,
  MONGO_URI: `mongodb://${env.MONGO_USER}:${env.MONGO_PASSWORD}@${env.MONGO_HOST}:${env.MONGO_PORT}/${env.MONGO_DATABASE}?authMechanism=DEFAULT&authSource=admin`,
  JWT_SECRET: env.JWT_SECRET,
  JWT_EXPIRY_TIME: env.JWT_EXPIRY_TIME || '1h',
  MIN_PASSWORD_LENGTH: parseInt(env.MIN_PASSWORD_LENGTH || 8, 10),
  PHONE_NUMBER_LENGTH: parseInt(env.MIN_PASSWORD_LENGTH || 10, 10),
  MINIO_ENDPOINT: env.MINIO_ENDPOINT,
  MINIO_PORT: parseInt(env.MINIO_PORT || 9000, 10),
  MINIO_ACCESS_KEY: env.MINIO_ACCESS_KEY,
  MINIO_SECRET_KEY: env.MINIO_SECRET_KEY,
  MINIO_USER_BUCKET: env.MINIO_USER_BUCKET,
  MINIO_RESTAURANT_BUCKET: env.MINIO_RESTAURANT_BUCKET,
  TEMP_UPLOAD_DIR: path.join(
    __dirname,
    `../${env.TEMP_UPLOAD_DIR}` || '../uploads'
  ),

  ALLOWED_ORIGINS: ['http://localhost:3000', 'http://0.0.0.0:3000'],

  USER_ROLES: { USER: 'user', B_USER: 'businessUser', ADMIN: 'admin' },
  GENDERS: { MALE: 'male', FEMALE: 'female', OTHER: 'other' },
  ALLOWED_IMAGE_TYPES: ['image/jpeg', 'image/png'],
  MAX_IMAGE_FILE_SIZE_IN_MB:
    parseInt(env.MAX_IMAGE_FILE_SIZE_IN_MB || 5, 10) * 1024 * 1024,
  INDIAN_STATES_AND_CITIES: {
    'Andhra Pradesh': [
      'Visakhapatnam',
      'Vijayawada',
      'Guntur',
      'Nellore',
      'Tirupati',
      'Kakinada',
      'Rajahmundry',
      'Anantapur',
      'Kadapa',
      'Kurnool',
    ],
    'Arunachal Pradesh': [
      'Itanagar',
      'Naharlagun',
      'Pasighat',
      'Tawang',
      'Ziro',
      'Bomdila',
      'Aalo',
      'Seppa',
    ],
    Assam: [
      'Guwahati',
      'Dibrugarh',
      'Silchar',
      'Jorhat',
      'Nagaon',
      'Tinsukia',
      'Tezpur',
      'Bongaigaon',
      'Karimganj',
    ],
    Bihar: [
      'Patna',
      'Gaya',
      'Bhagalpur',
      'Muzaffarpur',
      'Purnia',
      'Darbhanga',
      'Arrah',
      'Begusarai',
      'Katihar',
    ],
    Chhattisgarh: [
      'Raipur',
      'Bhilai',
      'Bilaspur',
      'Korba',
      'Durg',
      'Rajnandgaon',
      'Jagdalpur',
      'Raigarh',
    ],
    Goa: ['Panaji', 'Margao', 'Vasco da Gama', 'Mapusa', 'Ponda'],
    Gujarat: [
      'Ahmedabad',
      'Surat',
      'Vadodara',
      'Rajkot',
      'Bhavnagar',
      'Jamnagar',
      'Junagadh',
      'Gandhinagar',
      'Anand',
    ],
    Haryana: [
      'Gurugram',
      'Faridabad',
      'Panipat',
      'Ambala',
      'Yamunanagar',
      'Rohtak',
      'Hisar',
      'Karnal',
      'Sonipat',
    ],
    'Himachal Pradesh': [
      'Shimla',
      'Manali',
      'Dharamshala',
      'Solan',
      'Mandi',
      'Palampur',
      'Hamirpur',
      'Bilaspur',
    ],
    Jharkhand: [
      'Ranchi',
      'Jamshedpur',
      'Dhanbad',
      'Bokaro',
      'Deoghar',
      'Hazaribagh',
      'Giridih',
      'Ramgarh',
    ],
    Karnataka: [
      'Bengaluru',
      'Mysuru',
      'Mangaluru',
      'Hubballi',
      'Belagavi',
      'Kalaburagi',
      'Davanagere',
      'Ballari',
      'Tumakuru',
    ],
    Kerala: [
      'Thiruvananthapuram',
      'Kochi',
      'Kozhikode',
      'Thrissur',
      'Kollam',
      'Kannur',
      'Alappuzha',
      'Palakkad',
    ],
    'Madhya Pradesh': [
      'Bhopal',
      'Indore',
      'Gwalior',
      'Jabalpur',
      'Ujjain',
      'Sagar',
      'Ratlam',
      'Rewa',
      'Satna',
    ],
    Maharashtra: [
      'Mumbai',
      'Pune',
      'Nagpur',
      'Nashik',
      'Aurangabad',
      'Solapur',
      'Amravati',
      'Kolhapur',
      'Nanded',
    ],
    Manipur: [
      'Imphal',
      'Thoubal',
      'Bishnupur',
      'Churachandpur',
      'Kakching',
      'Ukhrul',
    ],
    Meghalaya: ['Shillong', 'Tura', 'Nongstoin', 'Jowai', 'Baghmara'],
    Mizoram: ['Aizawl', 'Lunglei', 'Saiha', 'Champhai', 'Serchhip'],
    Nagaland: [
      'Kohima',
      'Dimapur',
      'Mokokchung',
      'Tuensang',
      'Wokha',
      'Zunheboto',
    ],
    Odisha: [
      'Bhubaneswar',
      'Cuttack',
      'Rourkela',
      'Puri',
      'Sambalpur',
      'Balasore',
      'Baripada',
      'Bhadrak',
    ],
    Punjab: [
      'Ludhiana',
      'Amritsar',
      'Jalandhar',
      'Patiala',
      'Bathinda',
      'Hoshiarpur',
      'Mohali',
      'Moga',
    ],
    Rajasthan: [
      'Jaipur',
      'Jodhpur',
      'Udaipur',
      'Kota',
      'Ajmer',
      'Bikaner',
      'Bharatpur',
      'Alwar',
      'Sikar',
    ],
    Sikkim: ['Gangtok', 'Geyzing', 'Mangan', 'Namchi'],
    'Tamil Nadu': [
      'Chennai',
      'Coimbatore',
      'Madurai',
      'Tiruchirappalli',
      'Salem',
      'Tirunelveli',
      'Tiruppur',
      'Erode',
      'Vellore',
    ],
    Telangana: [
      'Hyderabad',
      'Warangal',
      'Nizamabad',
      'Khammam',
      'Karimnagar',
      'Mahbubnagar',
      'Nalgonda',
    ],
    Tripura: ['Agartala', 'Udaipur', 'Dharmanagar', 'Kailashahar'],
    'Uttar Pradesh': [
      'Lucknow',
      'Kanpur',
      'Varanasi',
      'Agra',
      'Meerut',
      'Prayagraj',
      'Bareilly',
      'Aligarh',
      'Moradabad',
    ],
    Uttarakhand: [
      'Dehradun',
      'Haridwar',
      'Haldwani',
      'Roorkee',
      'Rudrapur',
      'Kashipur',
    ],
    'West Bengal': [
      'Kolkata',
      'Howrah',
      'Darjeeling',
      'Siliguri',
      'Durgapur',
      'Asansol',
      'Malda',
      'Kharagpur',
    ],
  },
};

module.exports = config;
